### ISSUE TITLE
Does it work with Electron 23?

### ISSUE THREAD

**Issue by dj-fiorex** [poirierlouis/electron-bridge#2]
Hello, i wish to try your package because i liked the idea behind, but i did't be able to use it with electron v23
Tried to follow the Readme but i get an error in the preload.js
```
Unable to load preload script: C:\Users\user\Documents\NodeElectronReceiver\.webpack\renderer\main_window\preload.js
VM9 sandbox_bundle:2 ReferenceError: __dirname is not defined
    at <anonymous>:74:84
    at <anonymous>:83:12
    at runPreloadScript (VM9 sandbox_bundle:2:83095)
    at VM9 sandbox_bundle:2:83354
    at VM9 sandbox_bundle:2:83509
    at ___electron_webpack_init__ (VM9 sandbox_bundle:2:83513)
    at VM9 sandbox_bundle:2:83636
```
Do you have any ideas?

**Comment by poirierlouis** [comment]
Hi,

I have not been using it myself for a while.
I'll look into this.

Did you first try to run the `demo/`?

Edit: I just released v1.1.0 and the demo worked with ElectronJS v23.
Please let me know if you have trouble running the `demo\`.

**Comment by dj-fiorex** [comment]
Hello, thanks for your time, it was my fault, wrong webpack config. i have another problem now:
this is my config in directory: src/bridges/bridge.config.json
```
{
    "base": ".",
    "tsconfig": "tsconfig.json",
    "schemas": "src/bridges/schemas/", // TRIED WITH / and WITHOUTH
    "output": "src/bridges/generated/", // TRIED WITH / and WITHOUTH
    "main": false,
    "verbose": true
  }
```
and this is a sample schema with the path src/bridges/schema/sample.ts
```
import { Schema } from "@lpfreelance/electron-bridge-cli";
import { LogFunctions } from "electron-log";
import { SerialPortModule } from "../../main/serial";
@Schema(true)
export class SerialPort {
  constructor(private log: LogFunctions) {}

  public async refreshSerial(): Promise<string[]> {
    this.log.info("refreshSerial");
    return SerialPortModule.listPorts().then((ports) =>
      ports.map((port) => port.path)
    );
    // return ["COM3", "COM4"];
  }
}
```
The problem is the generated bridge (in directory src/bridges/generated/main/sample.bridge.ts) has wrong import for `SerialPortModule`:
```
import {Bridge} from "@lpfreelance/electron-bridge/main";
import {ipcMain} from "electron";
import {LogFunctions} from "electron-log";
import {SerialPortModule} from "../../main/serial"; //IT SHOULD BE "../../../main/serial"!!!!!!

export class SerialPortBridge implements Bridge {
    constructor(private log: LogFunctions) {
    }

    public register(): void {
        ipcMain.handle('eb.serialPort.refreshSerial', async () => {
            this.log.info("refreshSerial");
            return SerialPortModule.listPorts().then((ports) =>
                ports.map((port) => port.path)
            );
        });
    }

    public release(): void {
        ipcMain.removeHandler('eb.serialPort.refreshSerial');
    }
}

```

*UPDATE*

if i change my config to:
```
{
    "base": ".",
    "tsconfig": "tsconfig.json",
    "schemas": "src/bridges/schemas/",
    "output": "src/bridges/", // TRIED WITH / and WITHOUTH
    "main": false,
    "verbose": true
  }
```
the file is generated correctly, so maybe you could check if output has some nested folder. Hope this helps you find the bug!

*UPDATEx2*

With the latest version of the config there is another problem with another bridge, `settings.ts`, 
SCHEMA:
```
import { StoreType } from "../../store/settings.store";
```
GENERATED:
```
import {StoreType} from "src/store/settings.store"; // SHOULD BE ->  "../../store/settings.store";
```

Same things for renderer/settings.api.ts

Thanks again

**Comment by poirierlouis** [comment]
> [...] it was my fault, wrong webpack config

If it is possible, could you describe with a minimal example what produced the error and what you changed to fix it? This would pave the road for others who might face the same issue later. I'll close this issue after your response.

> i have another problem now: [...]

This is unrelated to this issue and it is about the other package `electron-bridge-cli`.
Can you please fill a new issue? I'll write a document about contributions so it can be clear for newcomers.
However, I'll check this problem, and I'll respond to you in the upcoming issue.

**Comment by poirierlouis** [comment]
@dj-fiorex , I've updated the README with a note at the end of the section in [cli - configuration](https://github.com/poirierlouis/electron-bridge/tree/master/cli#configuration).
If you still have problems regarding relative path after using my advice, please open a new issue.
